### ISSUE TITLE
TODO list: Google table

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#32]
- [x] fix the wrong id in `relation/Passive` sheet (this is the only error that causes validation fail) 
```
ERROR ParlaMint-UA-listOrg: ERROR: Can't find local id for relation/@Passive="#фракція #політичної #партії #„Вперед, #Україно!”"
```
- [x] add representative and member affiliation end (sometimes are persons affiliated with multiple parties at the same time)
- [x] add relation(`representing`) between parliamentary groups and political parties

**Comment by AnnaParla** [comment]
>  add representative and member affiliation end (sometimes are persons affiliated with multiple parties at the same time)

It is actually next to impossible to establish when an affiliation ends in a number of cases. The start date can be linked to a new political cycle or a major political event and this information is often published somewhere. But there are very few cases when a end date/year of their affiliation with a political party is identifiable. I understand it as a coding issue, but not sure how to handle it from my end.

**Comment by matyaskopp** [comment]
> It is actually next to impossible to establish when an affiliation ends in a number of cases. The start date can be linked to a new political cycle or a major political event and this information is often published somewhere. But there are very few cases when a end date/year of their affiliation with a political party is identifiable. I understand it as a coding issue, but not sure how to handle it from my end.

ok, I will check it

**Comment by matyaskopp** [comment]
- [ ] finalize `guest` sheet - include persons (remove 1 from exclude column)

I have added sheet `mismatch-20230220` that contain current mismatching persons, there are some new persons.

- [ ] `speaker-person` sheet - **only in cases when person is included, but not matched !!!**

**Comment by AnnaParla** [comment]
< finalize guest sheet - include persons (remove 1 from exclude column)>

1. I have included all deputyMinisters to the person list and affiliation list, since we agreed that they are part of the govt.  
a) I haven't deleted them from the guest list yet, but my understanding is that I should. Right? If yes, I will do it asap and let you know. 
Shall I create a separate issue for it? 
b) I also have to finalize from / to affiliation periods for the deputyMinisters on the affiliation list. I found a way to look for this information, but it is time-consuming. Hopefully, I will finish is today/tomorrow.

**Comment by AnnaParla** [comment]
< finalize guest sheet - include persons (remove 1 from exclude column)>

2. As for removing 1 from the guest list (now there are 17 instances), I need further agreement/confirmation from you re:
a) 5 out of 17 instances
MPs that appeared on that list incl. the MPs throughout the whole term and the MPs who served only part of the term and then changed their affiliation / spoke as guests and not as MPs. 
Shall they stay excluded/ be included / put to a separate speaker - person list like РЕФАТ ЧУБАРОВ?   
 
b) 4 out of 17 instances 
Deputy ministers with 2 or more affiliations. 
ВадимАнатолійовичТроян.1979 is the most difficult. during terms 8 and 9 he was both deputy minister (govt , therefore , regular speaker) and National Police head or vice (guest speaker). For now, I reflected all these roles in the affiliation sheet,.
Shall I keep his deputy minister role + to/from in the affiliation list and his other occupations on the guest list (without from/to period, since we did not do it for quests)     

c) 8 out of 17 instances
Various issues with spelling / categorizing names as they appear in the transcripts, including misspelt last names, wrong patronymic initials, second forenames or multiple last names (УрсулафондерЛяєн.1958), or only first names for some religious leaders. Shal I just remove 1 next to this category of problems and let the code validate them automatically?

**Comment by AnnaParla** [comment]
< speaker-person sheet - only in cases when person is included, but not matched !!!>

Clarification needed. On what page is it included and on what page is it not matched?
